baizhi/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('baizhiapp/',include('baizhiapp.urls')),
    # path('')

]

baizhiapp/urls.py
from django.urls import path
from baizhiapp.views import *
app_name = 'baizhiapp'

urlpatterns = [
    path('introduce/',introduce,name = 'introduce'),
    path('login/',login,name = 'login'),
    path('main/',main,name = 'main'),
    path('menu/',menu,name = 'menu'),
    path('mainc/',mainc,name = 'mainc'),
    path('register/',register,name = 'register'),
    path('register_logic/',register_logic,name = 'register_logic'),
    path('login_logic/',login_logic,name = 'login_logic'),
    path('move_code/',move_code,name = 'move_code'),
    path('decorate/',decorate,name='decorate'),
]

baizhiapp/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class TTest(models.Model):
    userid = models.TextField(blank=True, null=True)
    employer_name = models.TextField(blank=True, null=True)
    stature = models.TextField(blank=True, null=True)
    gender = models.TextField(blank=True, null=True)
    age = models.TextField(blank=True, null=True)
    born = models.TextField(blank=True, null=True)
    jobname = models.TextField(blank=True, null=True)
    salary = models.TextField(blank=True, null=True)
    hope_location = models.TextField(blank=True, null=True)
    native_place = models.TextField(blank=True, null=True)
    certificate = models.TextField(blank=True, null=True)
    school = models.TextField(blank=True, null=True)
    profession = models.TextField(blank=True, null=True)
    experience = models.TextField(blank=True, null=True)
    now_location = models.TextField(blank=True, null=True)
    nationality = models.TextField(blank=True, null=True)
    politics_status = models.TextField(blank=True, null=True)
    job_status = models.TextField(blank=True, null=True)
    hope_industry = models.TextField(blank=True, null=True)
    hope_position = models.TextField(blank=True, null=True)
    job_category = models.TextField(blank=True, null=True)
    marital_status = models.TextField(blank=True, null=True)
    phone = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_test'


class TUser(models.Model):
    username = models.TextField(blank=True, null=True)
    usertel = models.TextField(blank=True, null=True)
    email = models.TextField(blank=True, null=True)
    password = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_user'


class TZpgg(models.Model):
    userid = models.TextField(blank=True, null=True)
    employer_name = models.TextField(blank=True, null=True)
    stature = models.TextField(blank=True, null=True)
    gender = models.TextField(blank=True, null=True)
    age = models.TextField(blank=True, null=True)
    born = models.TextField(blank=True, null=True)
    jobname = models.TextField(blank=True, null=True)
    salary = models.TextField(blank=True, null=True)
    hope_location = models.TextField(blank=True, null=True)
    native_place = models.TextField(blank=True, null=True)
    certificate = models.TextField(blank=True, null=True)
    school = models.TextField(blank=True, null=True)
    profession = models.TextField(blank=True, null=True)
    experience = models.TextField(blank=True, null=True)
    now_location = models.TextField(blank=True, null=True)
    nationality = models.TextField(blank=True, null=True)
    politics_status = models.TextField(blank=True, null=True)
    job_status = models.TextField(blank=True, null=True)
    hope_industry = models.TextField(blank=True, null=True)
    hope_position = models.TextField(blank=True, null=True)
    job_category = models.TextField(blank=True, null=True)
    marital_status = models.TextField(blank=True, null=True)
    phone = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_zpgg'


from django.utils import timezone

#访问网站的ip地址和次数
class User_ip(models.Model):
    ip=models.CharField(verbose_name='IP地址',max_length=30)    #ip地址
    count=models.IntegerField(verbose_name='访问次数',default=0) #该ip访问次数
    country = models.CharField(verbose_name='所在国家',max_length=30)
    location = models.CharField(verbose_name='地区',max_length=30)
    province = models.CharField(verbose_name='省份',max_length=30)
    city = models.CharField(verbose_name='城市',max_length=30)
    operator = models.CharField(verbose_name='所属运营商',max_length=30)

    class Meta:
        verbose_name = '访问用户信息'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.ip
class Userip(models.Model):
    ip=models.CharField(verbose_name='IP地址',max_length=30)    #ip地址
    count=models.IntegerField(verbose_name='访问次数',default=0) #该ip访问次数
    # country = models.CharField(verbose_name='所在国家',max_length=30)
    # location = models.CharField(verbose_name='地区',max_length=30)
    # province = models.CharField(verbose_name='省份',max_length=30)
    # city = models.CharField(verbose_name='城市',max_length=30)
    # operator = models.CharField(verbose_name='所属运营商',max_length=30)

    class Meta:
        verbose_name = '访问用户信息'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.ip

#网站总访问次数
class VisitNumber(models.Model):
    count=models.IntegerField(verbose_name='网站访问总次数',default=0) #网站访问总次数
    class Meta:
        verbose_name = '网站访问总次数'
        verbose_name_plural = verbose_name
    def __str__(self):
        return str(self.count)

#单日访问量统计
class DayNumber(models.Model):
    day=models.DateField(verbose_name='日期',default=timezone.now)
    count=models.IntegerField(verbose_name='网站访问次数',default=0) #网站访问总次数
    class Meta:
        verbose_name = '网站日访问量统计'
        verbose_name_plural = verbose_name
    def __str__(self):
        return str(self.day)

baizhiapp/views.py
import json
import uuid
# from datetime import timezone
# from time import timezone

from django.core import paginator
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.shortcuts import render,HttpResponse
# Create your views here.
from django.utils import timezone

from baizhiapp.models import TTest,TZpgg,TUser,VisitNumber,User_ip,DayNumber
from baizhiapp import models, checkIP
from lxml import etree
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_v1_5, PKCS1_OAEP
import base64


def decrypt_params(privkey,param):
    comfirm_param = base64.b64decode(param)
    # 私钥
    encrypted_key = RSA.import_key(privkey)
    cipher_rsa2 = PKCS1_v1_5.new(encrypted_key)
    data = cipher_rsa2.decrypt(comfirm_param,None)
    return bytes.decode(data)


def decorate(func):  # 修改网站访问量和访问ip等信息
    def inner(request,*args, **kwargs):
        try:
        # 每一次访问，网站总访问次数加一
            count_nums = VisitNumber.objects.filter(id=1)
            if count_nums:
                count_nums = count_nums[0]
                count_nums.count += 1
            else:
                count_nums = VisitNumber()
                count_nums.count = 1
            count_nums.save()
            # print(request.META)
            # 记录访问ip和每个ip的次数
            if 'HTTP_X_FORWARDED_FOR' in request.META:  # 获取ip
                client_ip = request.META['HTTP_X_FORWARDED_FOR']
                client_ip = client_ip.split(",")[0]  # 所以这里是真实的ip
            else:
                client_ip = request.META['REMOTE_ADDR']  # 这里获得代理ip
            d_client_ip={'ip': client_ip}
            # print(d_client_ip)

            ip_exist = User_ip.objects.filter(ip=str(client_ip))
            if ip_exist:  # 判断是否存在该ip
                uobj = ip_exist[0]
                uobj.country = checkIP.checkip(d_client_ip)[0]
                uobj.province = checkIP.checkip(d_client_ip)[1]
                uobj.city = checkIP.checkip(d_client_ip)[2]
                uobj.operator = checkIP.checkip(d_client_ip)[3]
                uobj.create_times=timezone.datetime.now()
                uobj.count += 1
            else:
                uobj = User_ip()
                uobj.ip = client_ip
                uobj.country=checkIP.checkip(d_client_ip)[0]
                uobj.province=checkIP.checkip(d_client_ip)[1]
                uobj.city=checkIP.checkip(d_client_ip)[2]
                uobj.operator=checkIP.checkip(d_client_ip)[3]
                uobj.create_times = timezone.datetime.now()
                uobj.count = 1
            uobj.save()

            # 增加今日访问次数
            date = timezone.now().date()
            today = DayNumber.objects.filter(day=date)
            if today:
                temp = today[0]
                temp.count += 1
            else:
                temp = DayNumber()
                temp.dayTime = date
                temp.count = 1
            temp.save()
        except:
            pass
        return func(request,*args, **kwargs)
    return inner


@decorate
def introduce(request):
    return render(request,'baizhiapp/introduce.html')

def login(request):

    return render(request,'baizhiapp/login.html')

@decorate
def main(request):
    # 生成密钥
    key = RSA.generate(1024)
    # 公钥
    exportKey = key.publickey().exportKey()
    # 私钥
    encrypted_key = key.exportKey()
    # 私钥和公钥放入session
    request.session['privkey'] = bytes.decode(encrypted_key)
    request.session['publickey'] = bytes.decode(exportKey)
    s = str(uuid.uuid4())
    sess = request.session.get('username')
    response = render(request,'baizhiapp/main.html',{'sess':sess})
    response.set_cookie('asd',s)  # 设置新cookie

    request.session['random'] =  s  # 后端记住随机串
    # print(s,'我存的cookie')
    return  response

@decorate
def menu(request):
    privkey = request.session.get('privkey')
    publickey = request.session.get('publickey')

    city=request.GET.get('city')
    job=request.GET.get('job')
    number = request.GET.get('number')
    if number:
        number = number.replace(' ','+')
        print('加密的numberrrrrrrrrrrrr', number)
        number = decrypt_params(privkey,number)
        print('解密后的',number)
    # numebr = decrypt_params()
    print(city, job, '77777777777777777')
    if len(job) >10 or len(city)>10:
        city = city.replace(' ','+')
        job = job.replace(' ','+')
        city = decrypt_params(privkey,city)
        job = decrypt_params(privkey,job)
        print('解密后城市工作',city,job)

    # print(request.META,'sssss')
    # select=TZpgg.objects.filter(hope_location=city,hope_position=job)
    user_agent=request.META['HTTP_USER_AGENT']


    ran_cookie = request.COOKIES.get('asd')  # 从浏览器中获得的上次存进去的
    ran_session = request.session.get('random')  # 从数据库中拿出随机cookie值
    print(ran_session)
    # employers = TZpgg.objects.all().order_by("-id")

    employers = TZpgg.objects.filter(hope_location=city,hope_position__icontains=job)

    if 'python' in user_agent:
        return HttpResponse('asdhjaksf')
    if not number:
        number = 1
    pagtor = Paginator(employers, per_page=10)

    if ran_cookie == ran_session:
        page = pagtor.page(int(number))
        resp = render(request,'baizhiapp/menu.html',{'page':page,'employers':employers,'number':number,'city':city,'job':job,'publickey':publickey})
        s = str(uuid.uuid4())
        resp.set_cookie('asd',s)
        request.session['random'] = s
        return resp
    else:
        page = pagtor.page(1)
        print(city,job,'qqqqqqqqqqqqqqqqq')
        return  render(request,'baizhiapp/menu.html',{'page':page,'employers':employers,'number':number,'city':city,'job':job,'publickey':publickey})

def register(request):
    return render(request,'baizhiapp/register.html')

def register_logic(request):
    username = request.POST.get('username')
    usertel = request.POST.get('usertel')
    email = request.POST.get('email')
    password = request.POST.get('password')
    dataname = TUser.objects.filter(username=username)
    if not dataname:
        new_user = models.TUser.objects.create(username=username,usertel=usertel,email=email,password=password)
        print(new_user)
        if new_user:
            return redirect('baizhiapp:login')
    return redirect('baizhiapp:register')

def login_logic(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    dataname = TUser.objects.filter(username=username)
    datapwd = TUser.objects.filter(password=password)
    if dataname and datapwd:
        request.session['username'] = username
        return redirect('baizhiapp:main')
    return redirect('baizhiapp:login')
#



from aliyunsdkcore import client
from aliyunsdkafs.request.v20180112 import AuthenticateSigRequest
from aliyunsdkcore.profile import region_provider

def move_code(request):   #登录验证
    sessionid = request.GET.get('csessionid')
    sig = request.GET.get('sig')
    token = request.GET.get('nc_token')
    region_provider.add_endpoint('afs', 'cn-hangzhou', 'afs.aliyuncs.com')

    clt = client.AcsClient('LTAIXrRJT7ikiMG7','mJpj344qlvwy33ImCikjVoAYvNaN5K','cn-hangzhou')
    request = AuthenticateSigRequest.AuthenticateSigRequest()


    #必填参数：从前端获取，不可更改，android和ios只传这个参数即可
    request.set_SessionId(sessionid)
    #必填参数：从前端获取，不可更改
    request.set_Sig(sig)
    #必填参数：从前端获取，不可更改
    request.set_Token(token)
    #必填参数：从前端获取，不可更改
    request.set_Scene('nc_login')
    #必填参数：后端填写
    request.set_AppKey('FFFF0N00000000007F75')
    #必填参数：后端填写
    request.set_RemoteIp('192.168.73.1')

    result = clt.do_action_with_exception(request)  # 返回code 100表示验签通过，900表示验签失败
    print(result,'asdasdasdasd')
    # html = etree.HTML(result)
    # code = html.xpath('//code/text()')[0]
    code = json.loads(result)['Code']
    return HttpResponse('%s' % code)



def mainc(request):
    # try:
        cj=request.GET.get('cj')#获取前端传来的下拉框值
        searchtext=request.GET.get('searchtext')#获取前端传来的搜索词
        number = request.GET.get("number")  # 获取前端传来的页码
        if not number:  # 判断如果页面为空的话
            number = 1  # 页码的值默认为1
        if cj=='城市':
            select = TZpgg.objects.filter(hope_location__icontains=searchtext)
        elif cj=='职位':
            select = TZpgg.objects.filter(hope_position__icontains=searchtext)
        elif cj=='--请选择--':
            if searchtext in '北京':
                select = TZpgg.objects.filter(hope_location__icontains=searchtext)
            elif searchtext in '上海':
                select=TZpgg.objects.filter(hope_location__icontains=searchtext)
            elif searchtext in '广州':
                select=TZpgg.objects.filter(hope_location__icontains=searchtext)
            elif searchtext in '深圳':
                select=TZpgg.objects.filter(hope_location__icontains=searchtext)
            elif searchtext in '平面设计':
                select=TZpgg.objects.filter(hope_position__icontains=searchtext)
            elif searchtext in '软件工程师':
                select=TZpgg.objects.filter(hope_position__icontains=searchtext)
            elif searchtext in 'Java开发工程师':
                select=TZpgg.objects.filter(hope_position__icontains=searchtext)
            elif searchtext in '软件测试':
                select=TZpgg.objects.filter(hope_position__icontains=searchtext)
        elif not searchtext:
            select = TZpgg.objects.all()
        else:
            return HttpResponse('您输入的查询不到')
        pagtor = Paginator(select, per_page=30)  # 将查询到的数据进行每一页30条数据划分
        page=pagtor.page(number)
        print(cj,searchtext)
        return render(request,'baizhiapp/menu.html',{'select':select,'page':page,'number':number,})

templates/baizhiapp/introduce.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>百智招聘</title>
<link href="{% static '/style/authority/basic_layout.css' %}" rel="stylesheet" type="text/css">
<link href="{% static '/style/authority/common_style.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
	<div id="container">
		<table class="table" cellspacing="0" cellpadding="0" width="100%" align="center"  border="0">
		    <tr>
		      <th colspan="2">系统版本</th>
		    </tr>
		    <tr>
		      <td width="100" height="30">当前版本<span class="TableRow2"></span></td>
		      <td style="text-align:left">百智招聘系统 4.1</td>
		    </tr>
		</table>
		
	</div>

</body>
</html>

templates/baizhiapp/login.html
<!doctype html>
{% load static %}
<html>
<head>
<title>Home</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- font files  -->
<link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Nunito:400,300,700' rel='stylesheet' type='text/css'>
<!-- /font files  -->
<!-- css files -->
<link href="{% static '/css/style.css' %}" rel='stylesheet' type='text/css' media="all" />
<!-- /css files -->
 <script type="text/javascript" charset="utf-8" src="//g.alicdn.com/sd/ncpc/nc.js?t=2015052012"></script>
    <script type="text/javascript" src="{% static 'jquery.1.8.3.min.js' %}"></script>
</head>
<body>
<h1>Login</h1>
<div class="log">
	<div class="content1">
		<h2>Login</h2>
        <input id="code" type="hidden" value="900">
		<form id="fm" method="post" action="{% url 'baizhiapp:login_logic' %}">
            {% csrf_token %}

			<input type="text" name="username" value="USERNAME" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'USERNAME';}">
            <input type="password" name="password" value="PASSWORD" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'PASSWORD';}">
             <div id="your-dom-id" class="nc-container" style="margin-left: 60px;margin-top: 20px"></div> <!--No-Captcha渲染的位置，其中 class 中必须包含 nc-container-->


            <div class="button-row">
                <input  class="sign-in" value="Sign In"  onclick="form_submit()">

				<input type="reset" class="reset" value="Reset">

				<div class="clear"></div>
            </div>

		</form>
	</div>

	<div class="clear"></div>
</div>
<div class="footer">
	<p>Copyright &copy;  <a href="http://www.baizhiedu.com/" target="_blank" title="百知教育">百知教育</a></p>
</div>

    	<script type="text/javascript">
        var nc_token = ["FFFF0N00000000007F75", (new Date()).getTime(), Math.random()].join(':');
        var NC_Opt =
        {
            renderTo: "#your-dom-id",
            appkey: "FFFF0N00000000007F75",
            scene: "nc_login",
            token: nc_token,
            customWidth: 300,
            trans:{"key1":"code0"},
            elementID: ["usernameID"],
            is_Opt: 0,
            language: "cn",
            isEnabled: true,
            timeout: 3000,
            times:5,
            apimap: {
                // 'analyze': '//a.com/nocaptcha/analyze.jsonp',
                // 'get_captcha': '//b.com/get_captcha/ver3',
                // 'get_captcha': '//pin3.aliyun.com/get_captcha/ver3'
                // 'get_img': '//c.com/get_img',
                // 'checkcode': '//d.com/captcha/checkcode.jsonp',
                // 'umid_Url': '//e.com/security/umscript/3.2.1/um.js',
                // 'uab_Url': '//aeu.alicdn.com/js/uac/909.js',
                // 'umid_serUrl': 'https://g.com/service/um.json'
            },
             callback: function (data) {
                window.console && console.log(nc_token)
                window.console && console.log(data.csessionid)
                window.console && console.log(data.sig)
                url = "{% url 'baizhiapp:move_code' %}?nc_token="+nc_token+'&csessionid='+data.csessionid+'&sig='+data.sig
                var xhr;
                if(window.ActiveXObject){
                    xhr = new ActiveXObject("Microsoft.XMLHTTP")
                }else if(window.XMLHttpRequest){
                    xhr = new XMLHttpRequest()
                }
                xhr.open("get",url,true);
                xhr.send();
                xhr.onreadystatechange=function()
                {
                if (xhr.readyState==4 && xhr.status==200)
                {
                var text = xhr.responseText;   //获得字符串形式的响应数据
                    console.log(text,'qqqqq')
                    document.getElementById('code').value = '100'
    }
}
            }
        }

        var nc = new noCaptcha(NC_Opt)
        nc.upLang('cn', {
            _startTEXT: "请按住滑块，拖动到最右边",
            _yesTEXT: "验证通过",
            _error300: "哎呀，出错了，点击<a href=\"javascript:__nc.reset()\">刷新</a>再来一次",
            _errorNetwork: "网络不给力，请<a href=\"javascript:__nc.reset()\">点击刷新</a>",
        })


            function form_submit() {
                var code = document.getElementById('code').value;
                if (code==='100'){
                    $("form").submit()
                }
            }
        </script>


</body>
</html>

templates/baizhiapp/menu.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="{% static '/scripts/jquery/jquery-1.7.1.js' %}"></script>
<link href="{% static '/style/authority/basic_layout.css' %}" rel="stylesheet" type="text/css">
<link href="{% static '/style/authority/common_style.css' %}" rel="stylesheet" type="text/css">
<script type="text/javascript" src="{% static '/scripts/authority/commonAll.js' %}"></script>
<script type="text/javascript" src="{% static '/scripts/fancybox/jquery.fancybox-1.3.4.js' %}"></script>
<script type="text/javascript" src="{% static '/scripts/fancybox/jquery.fancybox-1.3.4.pack.js' %}"></script>
    <script type="text/javascript"  src="{% static 'jsencrypt.min.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static '/style/authority/jquery.fancybox-1.3.4.css' %}" media="screen"></link>
<script type="text/javascript" src="{% static '/scripts/artDialog/artDialog.js?skin=default' %}"></script>
<title>百智招聘</title>

</head>
<body>
	<form id="submitForm" name="submitForm" action="" method="post">
		<input type="hidden" name="allIDCheck" value="" id="allIDCheck"/>
		<input type="hidden" name="fangyuanEntity.fyXqName" value="" id="fyXqName"/>
		<div id="container">
			<div class="ui_content">
				<div class="ui_text_indent">
					<div id="box_border">
						<div id="box_top">搜索</div>
						<div id="box_center">
							<select name="fangyuanEntity.fyXqCode" id="fyXq" class="ui_select01" onchange="getFyDhListByFyXqCode();">
                                <option value=""
                                >--请选择--</option>
                                <option value="">城市</option>
                                <option value="">职位</option>
                            </select>
							<input type="text" id="fyZldz" name="fangyuanEntity.fyZldz" class="ui_input_txt02" />
							<input type="button" value="查询" class="ui_input_btn01" onclick="search()" />
                            <input type="hidden" value="{{ publickey }}" id="publickey">
                            <input type="hidden" value="{{ city }}" id="city">
                            <input type="hidden" value="{{ job }}" id="job">
						</div>
					</div>
				</div>
			</div>
			<div class="ui_content">
				<div class="ui_tb">
					<table class="table" cellspacing="0" cellpadding="0" width="100%" align="center" border="0">
						<tr>
							
						
							<th>姓名</th>
							<th>性别</th>
							<th>年龄</th>
                            <th>工资</th>
                            <th>学校</th>
{#                            <th>专业</th>#}

							<th>户籍地</th>
{#							<th>现居住地</th>#}
							<th>期望城市</th>
                            <th>岗位</th>
                            <th>增加</th>
                            <th>删除</th>
                            <th>修改</th>
						</tr>
                            {% for foo in page %}
							<tr>
								<td>{{ foo.employer_name }}</td>
								<td>{{ foo.gender }}</td>
								<td>{{ foo.age }}</td>
                                <td>{{ foo.salary }}</td>
                                <td>{{ foo.school }}</td>
{#                                <td>{{ foo.profession }}</td>#}

								<td>{{ foo.native_place }}</td>
{#								<td>{{ foo.now_location }}</td>#}
								<td>{{ foo.hope_location }}</td>
                                <td>{{ foo.hope_position }}</td>
							</tr>
                        {% endfor %}
		
					</table>
				</div>
				<div class="ui_tb_h30">
					<div class="ui_flt" style="height: 30px; line-height: 30px;">
						共有
						<span class="ui_txt_bold04">{{ employers.count }}</span>
						条记录，当前第
						<span class="ui_txt_bold04">{{ page.number }}</span>
						页,共{{ page.paginator.num_pages }}页
					</div>
					<div class="ui_frt">
						<!--    如果是第一页，则只显示下一页、尾页 -->
						
{#							<input type="button" value="首页" class="ui_input_btn01" />#}
                        <a href="{% url 'baizhiapp:menu' %}?number=1&city={{ city }}&job={{ job }}">首页</a>
                        {% if page.has_previous %}
{#							<input  type="button" value="上一页" class="ui_input_btn01"  />#}
                            <a href="{% url 'baizhiapp:menu' %}?number={{ page.previous_page_number }}&city={{ city }}&job={{ job }}">上一页</a>
                        {% endif %}
                        {% if page.has_next %}
{#							<input type="button" value="下一页" class="ui_input_btn01"#}
{#								onclick="jumpNormalPage(2);" />#}
                            <a href="{% url 'baizhiapp:menu' %}?number={{ page.next_page_number }}&city={{ city }}&job={{ job }}" >下一页</a>
                        {% endif %}
{#							<input type="button" value="尾页" class="ui_input_btn01"#}
{#								onclick="jumpNormalPage(9);" />#}
                        <a href="{% url 'baizhiapp:menu' %}?number={{ page.paginator.num_pages }}&city={{ city }}&job={{ job }}">尾页</a>
							<!--     如果是最后一页，则只显示首页、上一页 -->

						转到第<input type="text" id="jumpNumTxt" class="ui_input_txt01"  oninput = "value=value.replace(/[^\d]/g,'')"/>页
{#							 <input type="button" class="ui_input_btn01" value="跳转" onclick="jumpInputPage(9);" />#}
                        <a href="javascript:void(0)" onclick="page_jump()">跳转</a>
					</div>
				</div>
			</div>
		</div>
	</form>

        <script>
        function jiami(param) {
            var encrypt =  new JSEncrypt();
            var publickey = document.getElementById('publickey').value;
            encrypt.setPublicKey(publickey)
            return encrypt.encrypt(param)
        }

        function page_jump() {
            var jumpNumTxt = document.getElementById("jumpNumTxt").value;
            number = Number(jumpNumTxt)
            if (number<= {{ page.paginator.num_pages }}) {
                var city = document.getElementById("city").value;
                var job = document.getElementById("job").value;
                console.log(city,job,'传入的')
                jumpNumTxt = jiami(jumpNumTxt);
                city = jiami(city)
                job = jiami(job)
                console.log('加密后参数',city,'aaaaa',job)
                location.href = '{% url 'baizhiapp:menu' %}?number='+jumpNumTxt+'&job='+job+'&city='+city;
            }
        }

        function search() {
            search_text = document.getElementById('fyZldz').value;
            cj=jQuery('#fyXq option:selected').text();
            {#alert(cj);#}
            {#alert(search_text);#}
            location.href = "{% url 'baizhiapp:mainc' %}?searchtext="+search_text+"&cj="+cj
        }


    </script>


</body>
</html>